---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey-config-map
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      run_hour = 15
      start_hour = 16
      end_hour = 17
      dry_run = false
      blacklisted_namespaces = ["kube-system", "kube-node-lease", "kube-public", "shared-databases"]
      whitelisted_namespaces = [ "default" ]
      [debug]
      enabled= true
      schedule_immediate_kill= true
